language: go
dist: focal

go:
- 1.18.x
- master

addons:
  sonarcloud:
    organization: "ulboralabs" # the key of the org you chose at step #3    

services:
  - docker

before_install:  
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t ulboralabs/ulboracms .


script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  - docker push ulboralabs/ulboracms:latest