#!/usr/bin/env node

var Client = require('node-rest-client').Client;

//client = new Client();

exports.doPost = function (json, callback) {
    console.log("addon get: " + JSON.stringify(json));
    var returnVal = {
        success: false,
        message: "",
        jsonResponse: null
    };

    var client = null;
    if (json.basicAuth) {
        var options_auth = {
            user: json.username,
            password: json.password
        };
        client = new Client(options_auth);
    } else {
        client = new Client();
    }
    var args = {
        data: json.jsonRequest,
        headers: {"Content-Type": "application/json"}
    };

    console.log("addon post url: " + json.url);
    console.log("addon post request: " + JSON.stringify(json.jsonRequest));
    client.post(json.url, args, function (data, res) {
        // parsed response body as js object
        console.log("data: " + data);
        // raw response
        //console.log("response: "+ JSON.stringify(response));
        returnVal.success = true;
        returnVal.jsonResponse = data;
        callback(returnVal);
    });
};

exports.doPut = function (json, callback) {
    console.log("addon get: " + JSON.stringify(json));
    var returnVal = {
        success: false,
        message: "",
        jsonResponse: null
    };

    var client = null;
    if (json.basicAuth) {
        var options_auth = {
            user: json.username,
            password: json.password
        };
        client = new Client(options_auth);
    } else {
        client = new Client();
    }
    var args = {
        data: json.jsonRequest,
        headers: {"Content-Type": "application/json"}
    };

    console.log("addon post url: " + json.url);
    console.log("addon post request: " + json.jsonRequest);
    client.put(json.url, args, function (data, res) {
        // parsed response body as js object
        console.log("data: " + data);
        // raw response
        //console.log("response: "+ JSON.stringify(response));
        returnVal.success = true;
        returnVal.jsonResponse = data;
        callback(returnVal);
    });
};

exports.doGet = function (json, callback) {
    console.log("addon get: " + JSON.stringify(json));
    var returnVal = {
        success: false,
        message: "",
        jsonResponse: null
    };
    var queryParameters = json.queryParameters;
    var pathParameters = json.pathParameters;
    var arguments = "";
    if (queryParameters !== undefined && queryParameters !== null && queryParameters.length > 0) {
        var moreParams = false;
        arguments += "?";
        for (var cnt = 0; cnt < queryParameters.length; cnt++) {
            if (moreParams) {
                arguments += "&";
            }
            var name = queryParameters[cnt].name;
            var val = queryParameters[cnt].value;
            arguments += (name + "=" + val);
            moreParams = true;
        }
    } else if (pathParameters !== undefined && pathParameters !== null && pathParameters.length > 0) {
        for (var cnt = 0; cnt < pathParameters.length; cnt++) {
            arguments += ("/" + pathParameters[cnt]);
        }
    }
    var url = json.url + arguments;
    var client = null;
    if (json.basicAuth) {
        var options_auth = {
            user: json.username,
            password: json.password
        };
        client = new Client(options_auth);
    } else {
        client = new Client();
    }
    console.log("addon get url: " + url);
    client.get(url, function (data, res) {
        // parsed response body as js object
        console.log("data: " + data);
        // raw response
        //console.log("response: "+ JSON.stringify(response));
        returnVal.success = true;
        returnVal.jsonResponse = data;
        callback(returnVal);
    });
};

exports.doDelete = function (json, callback) {
    console.log("addon get: " + JSON.stringify(json));
    var returnVal = {
        success: false,
        message: "",
        jsonResponse: null
    };
    var queryParameters = json.queryParameters;
    var pathParameters = json.pathParameters;
    var arguments = "";
    if (queryParameters !== undefined && queryParameters !== null && queryParameters.length > 0) {
        var moreParams = false;
        arguments += "?";
        for (var cnt = 0; cnt < queryParameters.length; cnt++) {
            if (moreParams) {
                arguments += "&";
            }
            var name = queryParameters[cnt].name;
            var val = queryParameters[cnt].value;
            arguments += (name + "=" + val);
            moreParams = true;
        }
    } else if (pathParameters !== undefined && pathParameters !== null && pathParameters.length > 0) {
        for (var cnt = 0; cnt < pathParameters.length; cnt++) {
            arguments += ("/" + pathParameters[cnt]);
        }
    }
    var url = json.url + arguments;
    var client = null;
    if (json.basicAuth) {
        var options_auth = {
            user: json.username,
            password: json.password
        };
        client = new Client(options_auth);
    } else {
        client = new Client();
    }
    console.log("addon delete url: " + url);
    client.delete(url, function (data, res) {
        // parsed response body as js object
        console.log("data: " + data);
        // raw response
        //console.log("response: "+ JSON.stringify(response));
        returnVal.success = true;
        returnVal.jsonResponse = data;
        callback(returnVal);
    });

};

